// Parsed playlist data from CSV - Format: [Track Name, Artist Names Semicolon-Separated]
const PLAYLIST_SONGS = [
['Tum Se Hi', 'Pritam;Mohit Chauhan;Irshad Kamil'],
['Tere Ho Ke Rahenge', 'Arijit Singh'],
['Phir Se (From "Dhurandhar The Revenge")', 'Shashwat Sachdev;Arijit Singh;Irshad Kamil'],
['Khamoshiyan', 'Jeet Gannguli;Arijit Singh;Rashmi Virag'],
['Iktara (From "Wake Up Sid")', 'Amit Trivedi;Kavita Seth;Amitabh Bhattacharya'],
['Tu Jaane Na', 'Pritam;Atif Aslam'],
['Raabta', 'Pritam;Arijit Singh'],
['Tujhe Bhula Diya', 'Vishal-Shekhar;Mohit Chauhan;Shekhar Ravjiani;Shruti Pathak'],
['Isq Risk', 'Sohail Sen;Rahat Fateh Ali Khan;Irshad Kamil'],
['Sanam Re (From "Sanam Re")', 'Mithoon;Arijit Singh'],
['Judaai', 'Sachin-Jigar;Rekha Bhardwaj;Arijit Singh;Priya Saraiya'],
['Agar Tum Saath Ho', 'Alka Yagnik;Arijit Singh'],
['Aye Khuda', 'Salim Merchant'],
['Ilahi', 'Pritam;Arijit Singh;Amitabh Bhattacharya'],
['Kabhi Kabhi Aditi', 'Rashid Ali'],
['Suno- Na Sangemarmar', 'Arijit Singh'],
['Jab Se Tere Naina', 'Monty Sharma;Shaan'],
['Baarish', 'Mohammed Irfan;Gajendra Verma;Mithoon'],
['Heeriye (feat. Arijit Singh)', 'Jasleen Royal;Arijit Singh;Dulquer Salmaan'],
['Tere Vaaste (From "Zara Hatke Zara Bachke")', 'Varun Jain;Sachin-Jigar;Shadab Faridi;Altamash Faridi;Amitabh Bhattacharya'],
['Sawan Aaya Hai', 'Tony Kakkar;Arijit Singh'],
['Subhanallah', 'Pritam;Sreerama Chandra;Shilpa Rao;Amitabh Bhattacharya'],
['Jeena Jeena (From "Badlapur")', 'Atif Aslam'],
['Hawayein (From "Jab Harry Met Sejal")', 'Pritam;Arijit Singh'],
['Kya Mujhe Pyar Hai (From "Woh Lamhe")', 'Pritam;KK'],
['Challa', 'A.R. Rahman;Rabbi;Gulzar'],
['Kalank (Title Track)', 'Arijit Singh'],
['Dil Mein Ho Tum', 'Armaan Malik'],
['Ae Dil Hai Mushkil Title Track', 'Pritam;Arijit Singh'],
['Bulleya (From "Ae Dil Hai Mushkil")', 'Pritam;Amit Mishra;Shilpa Rao'],
['Bekhayali (Arijit Singh Version) [From "Kabir Singh"]', 'Arijit Singh;Sachet-Parampara'],
['Khairiyat', 'Pritam;Arijit Singh'],
['Humsafar', 'Akhil Sachdeva;Mansheel Gujral'],
['Bolna (From "Kapoor & Sons (Since 1921)")', 'Tanishk Bagchi;Arijit Singh;Asees Kaur'],
['Galliyan (Unplugged) [From "Ek Villain"]', 'Shraddha Kapoor;Ankit Tiwari'],
['Duaa', 'Vishal-Shekhar;Nandini Srikar;Arijit Singh'],
['Tu Hai Ki Nahi', 'Ankit Tiwari;Abhendra Kumar Upadhyay'],
['Manali Trance', 'Yo Yo Honey Singh;Neha Kakkar'],
['Naina', 'Arijit Singh'],
['O Saiyyan', 'Ajay-Atul;Roop Kumar Rathod'],
['Ya Rabba (From "Salaam-E-Ishq")', 'Kailash Kher'],
['Main Hoon Hero Tera (Sad Version)', 'Armaan Malik;Amaal Mallik'],
['Tera Ban Jaunga', 'Akhil Sachdeva;Tulsi Kumar;Kumaar'],
['Zinda', 'Amit Trivedi'],
['Medley: Kehna Galat Galat / Halka Halka Suroor', 'Madhur Sharma;Nusrat Fateh Ali Khan'],
['Ke Bin Tere', 'Mithoon'],
['Tera Deedar Hua (From "Jannat 2")', 'Pritam;Anupam Amod;Rahat Fateh Ali Khan'],
['Teri Deewani', 'Kailash Kher;Paresh Kamath;Naresh Kamath'],
['Jaane Nahin Denge Tujhe', 'Sonu Nigam'],
['Sunn Raha Hai', 'Ankit Tiwari;Sandeep Nath'],
['Samjhawan', 'Jawad Ahmad;Shaarib Toshi;Arijit Singh;Shreya Ghoshal'],
['Pal', 'Javed-Mohsin;Arijit Singh;Shreya Ghoshal;Kunaal Vermaa;Prashant Ingole'],
['Hasi - Male Version', 'Ami Mishra;Kunaal Vermaa'],
['Abhi Mujh Mein Kahin', 'Ajay-Atul;Sonu Nigam'],
['Mere Nishaan (From "Oh My God")', 'Kailash Kher;Meet Bros Anjjan'],
['Khwahishein', 'Salim–Sulaiman;Shreya Ghoshal'],
['Tum Tak (From "Raanjhanaa")', 'A.R. Rahman;Javed Ali;KIRTI SAGATHIA;Pooja AV'],
['Tujh Mein Rab Dikhta Hai', 'Salim–Sulaiman;Roop Kumar Rathod;Jaideep Sahni'],
['Mast Magan', 'Arijit Singh;Chinmayi;Shankar-Ehsaan-Loy;Amitabh Bhattacharya'],
['Tera Rastaa Chhodoon Na', 'Vishal-Shekhar;Amitabh Bhattacharya;Anusha Mani'],
['Soch Na Sake', 'Arijit Singh'],
['Janam Janam', 'Pritam;Arijit Singh;Antara Mitra'],
['Moh Moh Ke Dhaage (Female)', 'Anu Malik;Monali Thakur;Varun Grover'],
['Moh Moh Ke Dhaage (Male)', 'Anu Malik;Papon;Varun Grover'],
['Manwa Laage', 'Vishal-Shekhar;Shreya Ghoswal;Arijit Singh;Irshad Kamil'],
['Mileya Mileya', 'Rekha Bhardwaj;Jigar Saraiya;Priya Andrews'],
['Malang (Title Track) [From "Malang - Unleash The Madness"]', 'Ved Sharma;Kunaal Vermaa'],
['Bol Do Na Zara', 'Armaan Malik;Amaal Mallik;Rashmi Virag'],
['Phir Mohabbat', 'Mohammed Irfan;Arijit Singh;Saim Bhat;Mithoon;Sayeed Quadri'],
['Kaun Tujhe (Armaan Malik Version)', 'Armaan Malik;Amaal Mallik'],
['Kaun Tujhe', 'Palak Muchhal;Amaal Mallik;Manoj Muntashir'],
['Shayad', 'Pritam;Arijit Singh'],
['Ek Ladki Ko Dekha Toh Aisa Laga (From "Ek Ladki Ko Dekha Toh Aisa Laga")', 'Darshan Raval;Rochak Kohli'],
['Main Rahoon Ya Na Rahoon', 'Amaal Mallik;Armaan Malik;Rashmi Virag'],
['Kyun Main Jaagoon', 'Shafqat Amanat Ali'],
['Dil Kyun Yeh Mera', 'KK'],
['Ijazat (From "One Night Stand")', 'Meet Bros.;Arijit Singh'],
['Pani Da Rang Male (From "Vicky Donor")', 'Ayushmann Khurrana'],
['Proper Patola (From "Proper Patola") (feat. Badshah)', 'Diljit Dosanjh;Badshah'],
['Blue Eyes', 'Yo Yo Honey Singh'],
['Love Dose', 'Yo Yo Honey Singh'],
['Brown Rang', 'Yo Yo Honey Singh'],
['Angreji Beat', 'Yo Yo Honey Singh;Gippy Grewal'],
['Amplifier', 'Imran Khan'],
['Udd Gaye - Bacardi House Party Sessions', 'Ritviz'],
['Main Rang Sharbaton Ka (From "Phata Poster Nikhla Hero")', 'Atif Aslam;Chinmayi;Pritam'],
['Mere Bina', 'Pritam;Nikhil D\'Souza'],
['Muskurane - Romantic', 'Jeet Gannguli;Arijit Singh;Rashmi Virag'],
['Shukran Allah', 'Salim–Sulaiman;Sonu Nigam;Shreya Ghoshal;Salim Merchant'],
['Titliaan', 'Afsana Khan;Avvy Sra;Harrdy Sandhu;Sargun Mehta'],
['Paniyon Sa', 'Rochak Kohli;Atif Aslam;Tulsi Kumar'],
['Kabira', 'Pritam;Tochi Raina;Rekha Bhardwaj;Amitabh Bhattacharya'],
['Bin Tere', 'Vishal-Shekhar;Shafqat Amanat Ali;Sunidhi Chauhan'],
['Enna Sona (From "OK Jaanu")', 'A.R. Rahman;Arijit Singh'],
['Mar Jawaan', 'Shruti Pathak;Salim Merchant'],
['Humdard', 'Arijit Singh;Mithoon'],
['Humnava Mere', 'Jubin Nautiyal;Manoj Muntashir'],
['Tum Ho', 'Mohit Chauhan;Suzanne D\'Mello'],
['Tum Mile', 'Pritam;Neeraj Shridhar'],
['Tune Jo Na Kaha', 'Pritam;Mohit Chauhan;Sandeep Shrivastava'],
['Ye Tune Kya Kiya', 'Pritam;Javed Bashir;Rajat Arora'],
['Yeh Jism', 'Ali Azmat'],
['Zara Zara', 'Omkar'],
['Teri Meri', 'Rahat Fateh Ali Khan;Shreya Ghoshal'],
['Khuda Jaane', 'Vishal-Shekhar;KK;Shilpa Rao;Anvita Dutt Guptan'],
['Sajdaa', 'Shankar-Ehsaan-Loy;Rahat Fateh Ali Khan;Shankar Mahadevan;Richa Sharma'],
['Kisi Se Pyar Ho Jaye', 'Jubin Nautiyal;Gourov-Roshin;Rajesh Roshan;Kumaar;Anand Bakshi'],
['Kaabil Hoon', 'Jubin Nautiyal;Palak Muchhal;Rajesh Roshan;Nasir Faraaz'],
['Shikayatein', 'Mohan Kannan;Amitabh Bhattacharya;Amit Trivedi'],
['Khaabon Ke Parinday', 'Alyssa Mendonsa;Mohit Chauhan'],
['Naina (From "Omkara")', 'Rahat Fateh Ali Khan'],
['Ishq Wala Love', 'Vishal-Shekhar;Shekhar Ravjiani;Salim Merchant;Neeti Mohan'],
['Jiya Re', 'A.R. Rahman;Neeti Mohan;Gulzar'],
['Tere Mast Mast Do Nain', 'Rahat Fateh Ali Khan'],
['Rehna Tu', 'A.R. Rahman;Prasoon Joshi'],
['Tera Hone Laga Hoon', 'Pritam;Atif Aslam;Alisha Chinai'],
['Be Intehaan', 'Atif Aslam;Sunidhi Chauhan;Pritam'],
['Chand Sifarish', 'Jatin-Lalit;Shaan;Kailash Kher;Prasoon Joshi'],
['Bakhuda Tumhi Ho', 'Atif Aslam;Alka Yagnik;Pritam'],
['Pee Loon', 'Pritam;Mohit Chauhan;Irshad Kamil'],
['Saiyyan', 'Kailash Kher;Paresh Kamath;Naresh Kamath'],
['Kun Faya Kun', 'A.R. Rahman;Javed Ali;Mohit Chauhan'],
['Thodi Jagah (From "Marjaavaan")', 'Arijit Singh;Tanishk Bagchi;Rashmi Virag'],
['Vaaste', 'Dhvani Bhanushali;Nikhil D\'Souza;Tanishk Bagchi'],
['Chahun Main Ya Naa', 'Palak Muchhal;Arijit Singh;Jeet Gannguli;Irshad Kamil'],
['Jashn-E-Bahaaraa', 'A.R. Rahman;Javed Ali'],
['Main Tera Dhadkan Teri', 'Pritam;KK;Hard Kaur;Sunidhi Chauhan'],
['Shaayraana', 'Pritam;Arijit Singh'],
['Dooriyan', 'Mohit Chauhan;Pritam'],
['Hale Dil', 'Harshit Saxena;Sayeed Quadri'],
['Dil Ibaadat', 'Pritam;KK;Sayeed Quadri'],
['Bheegi Si Bhaagi Si', 'Pritam;Mohit Chauhan;Antara Mitra'],
['Tu Hi Mera', 'Pritam;Shafqat Amanat Ali;Sayeed Quadri'],
['O Meri Jaan', 'Pritam;KK;Sayeed Quadri'],
['Tujhe Sochta Hoon', 'Pritam;KK;Sayeed Quadri'],
['Yaariyaan', 'Shilpa Rao;Mohan Kannan'],
['Kurbaan Hua', 'Salim–Sulaiman;Vishal Dadlani'],
['Hardum Humdum (From "Ludo")', 'Pritam;Arijit Singh'],
['Lut Gaye', 'Jubin Nautiyal;Tanishk Bagchi;Manoj Muntashir;Nusrat Fateh Ali Khan'],
['Satisfya', 'Imran Khan'],
['Sawaar Loon', 'Monali Thakur;Amit Trivedi'],
['Aabaad Barbaad (From "Ludo")', 'Pritam;Arijit Singh'],
['Masakali', 'Mohit Chauhan;A.R. Rahman;Prasoon Joshi'],
['Manchala', 'Vishal-Shekhar;Shafqat Amanat Ali;Nupur Pant'],
['Ambarsariya', 'Sona Mohapatra;Ram Sampath;Munna Dhiman'],
['Aas Paas Khuda', 'Vishal-Shekhar;Rahat Fateh Ali Khan'],
['Main Hoon Hero Tera (Armaan Malik Version)', 'Armaan Malik'],
['Hua Hain Aaj Pehli Baar', 'Amaal Mallik;Manoj Yadav;Armaan Malik;Palak Muchhal'],
['Koi Jaane Na (Title Track) [From "Koi Jaane Na"]', 'Amaal Mallik;Armaan Malik;Tulsi Kumar'],
['Main Agar Kahoon', 'Sonu Nigam;Shreya Ghoshal;Vishal-Shekhar;Javed Akhtar'],
['Safarnama', 'Lucky Ali'],
['Wajah Tum Ho', 'Armaan Malik;Baman;Manoj Muntashir'],
['Guzarish', 'A.R. Rahman;Javed Ali;Prasoon Joshi'],
['Yeh Dooriyan', 'Pritam;Mohit Chauhan'],
['Zaroorat', 'Mustafa Zahid;Mithoon'],
['Main Dhoondne Ko Zamaane Mein', 'Arijit Singh'],
['Banjaara (From "Ek Villain")', 'Mohammed Irfan'],
['Mehrama', 'Pritam;Darshan Raval;Antara Mitra'],
['In Dino', 'Pritam;Soham;Sayeed Quadri'],
['Rab Ka Shukrana', 'Pritam;Mohit Chauhan'],
['Ghar Se Nikalte Hi', 'Amaal Mallik;Armaan Malik;Kunaal Vermaa'],
['Tu Jo Mila', 'Pritam;KK;Kausar Munir'],
['Bhula Dena', 'Mustafa Zahid;Jeet Gannguli;Sanjay Masoom'],
['Meri Aashiqui', 'Palak Muchhal;Arijit Singh;Mithoon;Irshad Kamil'],
['Ae Zindagi Gale Laga Le - Take, 1', 'Ilaiyaraaja;Amit Trivedi;Arijit Singh'],
['Milne Hai Mujhse Aayi', 'Arijit Singh;Jeet Gannguli;Irshad Kamil'],
['Sunn Raha Hai (Female Version)', 'Shreya Ghoshal;Ankit Tiwari;Sandeep Nath'],
['O Saathi', 'Atif Aslam;Arko'],
['Woh Lamhe Woh Baatein', 'Atif Aslam'],
['Dekhte Dekhte', 'Atif Aslam;Nusrat Fateh Ali Khan;Rochak Kohli;Manoj Muntashir'],
['Piya O Re Piya', 'Sachin-Jigar;Atif Aslam;Shreya Ghoshal'],
['Jeene Laga Hoon', 'Sachin-Jigar;Atif Aslam;Shreya Ghoshal'],
['Tera Hua (From "Loveyatri")', 'Atif Aslam;Tanishk Bagchi'],
['Aao Milo Chalo', 'Pritam;Shaan;Ustad Sultan Khan;Irshad Kamil'],
['Saware (From "Phantom")', 'Pritam;Arijit Singh'],
['Nazar Na Lag Jaaye (From "Stree")', 'Ash King;Sachin-Jigar'],
['Main Agar', 'Pritam;Atif Aslam'],
['Tum Jab Paas', 'Prateek Kuhad'],
['Kaisi Hai Ye Rut', 'Srinivas'],
['Maahi Ve', 'A.R. Rahman'],
['Rihaa', 'Arijit Singh'],
['Liggi', 'Ritviz'],
['Buddhu Sa Mann', 'Amaal Mallik;Armaan Malik;Abhiruchi Chand'],
['Meri Tum Ho (Unplugged)', 'Pritam;Jubin Nautiyal;Ash King;Sandeep Shrivastava;Shloke Lal'],
['Pehla Pyaar', 'Armaan Malik;Vishal Mishra;Irshad Kamil'],
['Sab Tera', 'Armaan Malik;Shraddha Kapoor'],
['Jab Tak', 'Armaan Malik;Amaal Mallik;Manoj Muntashir'],
['Besabriyaan', 'Armaan Malik;Amaal Mallik;Manoj Muntashir'],
['Kuch Din', 'Jubin Nautiyal;Rajesh Roshan;Manoj Muntashir'],
['Dekh Lena', 'Arijit Singh;Tulsi Kumar;Ankit Tiwari;Manoj Muntashir'],
['Maula', 'Papon;Goldie Sohel'],
['Chashni (From "Bharat")', 'Abhijeet Srivastava;Vishal-Shekhar'],
['Mitwa', 'Shankar-Ehsaan-Loy;Shankar Mahadevan;Caralisa Monteiro;Shafqat Amanat Ali'],
['Roke Na Ruke Naina (From "Badrinath Ki Dulhania")', 'Arijit Singh'],
['Tum Hi Aana (From "Marjaavaan")', 'Payal Dev;Jubin Nautiyal;Kunaal Vermaa'],
['Sapna Jahan (From "Brothers")', 'Ajay-Atul;Sonu Nigam;Neeti Mohan'],
['Chale Aana (From "De De Pyaar De")', 'Amaal Mallik;Armaan Malik;Kunaal Vermaa'],
['Sab Tera Unplugged', 'Armaan Malik'],
['Rang Lageya', 'Mohit Chauhan;Rochak Kohli'],
['Chidiya', 'Vilen'],
['Galliyan (From "Ek Villain")', 'Ankit Tiwari'],
['Kabhi Jo Badal Barse', 'Arijit Singh'],
['Tum Hi Ho (From "Aashiqui 2")', 'Arijit Singh'],
['Tu Hi Hai', 'Amit Trivedi;Arijit Singh;Kausar Munir'],
['Tose Naina (From "Mickey Virus)', 'Arijit Singh'],
['Nadaan Parinde', 'A.R. Rahman;Mohit Chauhan'],
['Ranjha (From "Shershaah")', 'Jasleen Royal;B Praak;Romy'],
['Raataan Lambiyan (From "Shershaah")', 'Tanishk Bagchi;Jubin Nautiyal;Asees Kaur'],
['Kabhii Tumhhe', 'Javed-Mohsin;Darshan Raval;Rashmi Virag'],
['Bhare Naina', 'Vishal-Shekhar;Nandini Srikar;Panchhi Jalonvi'],
['Ye Ishq Hai', 'Pritam;Shreya Ghoshal;Irshad Kamil'],
['Chaar Kadam', 'Shaan;Shreya Ghoshal;Shantanu Moitra;Swanand Kirkire'],
['Mere Yaaraa (From "Sooryavanshi")', 'Arijit Singh;Neeti Mohan;Rashmi Virag'],
['Ik Vaari Aa', 'Pritam;Arijit Singh;Amitabh Bhattacharya'],
['Barsaat', 'Armaan Malik;Amaal Mallik'],
['Tu Mera Hogaya Hai (From "Tadap")', 'Pritam;Jubin Nautiyal'],
['Mere Liye Tum Kaafi Ho (From "Shubh Mangal Zyada Saavdhan")', 'Ayushmann Khurrana;Tanishk-Vayu'],
['Tumse Bhi Zyada (From "Tadap")', 'Pritam;Arijit Singh'],
['Rait Zara Si (From "Atrangi Re")', 'A.R. Rahman;Arijit Singh;Shashaa Tirupati'],
['Kiston (From "Roohi")', 'Sachin-Jigar;Jubin Nautiyal'],
['Haule Haule', 'Salim–Sulaiman;Sukhwinder Singh;Jaideep Sahni'],
['O Re Piya', 'Salim–Sulaiman;Rahat Fateh Ali Khan;Jaideep Sahni'],
['Kalle Kalle (From "Chandigarh Kare Aashiqui")', 'Priya Saraiya;Sachin-Jigar'],
['Chaka Chak', 'Shreya Ghoshal;A.R. Rahman;Irshad Kamil'],
['Tera Hua (From "Cash")', 'Arijit Singh;Akull;Riya Duggal'],
['Meri Zindagi Hai Tu (From "Satyameva Jayate 2")', 'Rochak Kohli;Jubin Nautiyal;Neeti Mohan;Manoj Muntashir'],
['Maa', 'Shankar Mahadevan;Shankar-Ehsaan-Loy;Prasoon Joshi'],
['Mere Rashke Qamar', 'Nusrat Fateh Ali Khan;Rahat Fateh Ali Khan;Tanishk Bagchi;A1 Melody Master-Fana;Manoj Muntashir'],
['Pareshaan', 'Amit Trivedi;Shalmali Kholgade;Kausar Munir'],
['Tera Chehra', 'Adnan Sami'],
['Itni Si Baat Hain (From "Azhar")', 'Pritam;Arijit Singh;Antara Mitra;Manoj Yadav'],
['Hosanna', 'A.R. Rahman;Leon D\'souza;Suzanne D\'Mello'],
['Har Kisi Ko (Female)', 'Arijit Singh;Neeti Mohan;Chirantan Bhatt;Kalyanji-Anandji;Manoj Yadav'],
['Saanson Ko (From "Zid")', 'Shaarib Toshi;Arijit Singh'],
['Meri Jaan', 'Sanjay Leela Bhansali;Neeti Mohan'],
['Allah Waariyan', 'Shafqat Amanat Ali;Arko Pravo Mukherjee'],
['Soch Liya', 'Mithoon;Arijit Singh;Manoj Muntashir'],
['Woh Ladki Hai Kahan', 'Shaan;Kavita Krishnamurthy'],
['Channa Mereya', 'Pritam;Arijit Singh'],
['Yaariyan (reprise)', 'Sunidhi Chauhan;Arijit Singh;Pritam'],
['Raanjhanaa', 'Imdad Hussain;Deep Joshi'],
['Mausam', 'Mithoon;Sayeed Quadri'],
['Phir Se Ud Chala', 'Mohit Chauhan'],
['Tum Jo Aaye', 'Pritam;Rahat Fateh Ali Khan;Tulsi Kumar;Irshad Kamil'],
['Jee Le Zaraa', 'Vishal Dadlani;Ram Sampath;Javed Akhtar'],
['Kaise Hua (From "Kabir Singh")', 'Vishal Mishra;Manoj Muntashir'],
['Zindagi Kuch Toh Bata (Reprise)', 'Pritam;Jubin Nautiyal;Neelesh Misra'],
['Kasoor - Acoustic', 'Prateek Kuhad'],
['Breathless - Shankar Mahadevan', 'Shankar Mahadevan'],
['Pehli Dafa', 'Atif Aslam;Shiraz Uppal;Shakeel Sohail'],
['Shukriya', 'Jeet Gannguli;Jubin Nautiyal'],
['Beete Lamhein', 'KK;Mithoon;Sayeed Quadri'],
['Zehnaseeb', 'Vishal-Shekhar;Chinmayi;Shekhar Ravjiani'],
['Ishq Bulaava', 'Vishal-Shekhar;Sanam Puri;Shipra Goyal'],
['Such Keh Raha Hai', 'KK'],
['Sach Keh Raha Hai - LoFi Flip', 'KK'],
['O Mere Dil Ke Chain - LoFi', 'Sanam'],
['Saibo', 'Sachin-Jigar;Shreya Ghoshal;Tochi Raina'],
['Dildaara (Stand By Me)', 'Vishal-Shekhar;Shafqat Amanat Ali;Kumaar'],
['Saware', 'Pritam;Arijit Singh'],
['Darasal', 'Atif Aslam;Jam8;Irshad Kamil'],
['Saiyaara', 'Sohail Sen;Mohit Chauhan;Tarannum Malik Jain;Kausar Munir'],
['Dagabaaz Re', 'Rahat Fateh Ali Khan;Shreya Ghoshal'],
['Ajab Si', 'KK;Vishal-Shekhar;Vishal Dadlani'],
['Gulabi', 'Sachin-Jigar;Jigar Saraiya;Priya Saraiya;Jaideep Sahni'],
['Chori Kiya Re Jiya', 'Sonu Nigam;Shreya Ghoshal'],
['Dil Diyan Gallan', 'Vishal-Shekhar;Atif Aslam;Irshad Kamil'],
['Kho Gaye', 'Taaruk Raina;Mismatched - Cast'],
['Akhiyaan', 'Mitraz'],
['Jiyein Kyun', 'Pritam;Papon'],
['Naina', 'Sona Mohapatra;Armaan Malik'],
['Tujhe Kitna Chahne Lage (From "Kabir Singh")', 'Arijit Singh;Mithoon'],
['Phir Kabhi', 'Arijit Singh;Amaal Mallik;Manoj Muntashir'],
['Teri Ore', 'Pritam;Rahat Fateh Ali Khan;Shreya Ghoshal;Mayur Puri'],
['Baatein Ye Kabhi Na - Male', 'Jeet Gannguli;Arijit Singh;Sayeed Quadri'],
['Faasle', 'Aditya Rikhari'],
['Zara Sa', 'Pritam;KK;Sayeed Quadri'],
['Laal Ishq', 'Sanjay Leela Bhansali;Arijit Singh;Siddharth - Garima'],
['Lo Maan Liya', 'Arijit Singh'],
['Tu Hi Haqeeqat', 'Pritam;Javed Ali;Irshan Ashraf;Shadab;Sayeed Quadri'],
['Kholo Kholo', 'Raman Mahadevan;Shankar-Ehsaan-Loy;Prasoon Joshi'],
['Duniyaa', 'Akhil;Dhvani Bhanushali;Kunaal Vermaa'],
['Sanu Ek Pal Chain', 'Rahat Fateh Ali Khan;Tanishk Bagchi;Nusrat Fateh Ali Khan;Manoj Muntashir'],
['Sapna Jahan', 'Ajay-Atul;Sonu Nigam;Neeti Mohan'],
['Tu Har Lamha (From "Khamoshiyan")', 'Bobby-Imran;Arijit Singh;Sayeed Quadri'],
['Taare Zameen Par', 'Shankar Mahadevan;Dominique;Vivieanne Pocha;Shankar-Ehsaan-Loy;Prasoon Joshi'],
['Surili Akhiyon Wale - Duet', 'Sajid-Wajid;Rahat Fateh Ali Khan;Sunidhi Chauhan;Suzanne D\'Mello;Gulzar'],
['Choo Lo', 'The Local Train'],
['Jannatein Kahan', 'Pritam;KK;Mayur Puri'],
['Raaton', 'Aditya Rikhari'],
['Tum Kya Mile (From "Rocky Aur Rani Kii Prem Kahaani")', 'Pritam;Arijit Singh;Shreya Ghoshal;Amitabh Bhattacharya'],
['Tumhe Kitna Pyaar Karte (From "Bawaal")', 'Mithoon;Arijit Singh;Manoj Muntashir'],
['Kabhii Tumhhe (From "Shershaah")', 'Javed-Mohsin;Darshan Raval;Rashmi Virag'],
['Saadi Galli Aaja', 'Rochak Kohli;Ayushmann Khurrana;Neeti Mohan'],
['Pehli Nazar Mein', 'Atif Aslam;Pritam'],
['Tu hai kahan', 'AUR'],
['Hamari Adhuri Kahani (Title Track) [From "Hamari Adhuri Kahani"]', 'Jeet Gannguli;Arijit Singh;Rashmi Virag'],
['Lambiyaan Si Judaiyaan', 'Arijit Singh;Shadab;Altamash Faridi;Jam8;Amitabh Bhattacharya'],
['Tere Pyaar Mein', 'Pritam;Arijit Singh;Amitabh Bhattacharya;Nikhita Gandhi'],
['Kya Karoon?', 'Shankar-Ehsaan-Loy;Clinton Cerejo;Dominique Cerejo;Loy Mendonsa'],
['Kyon', 'Pritam;Papon;Sunidhi Chauhan'],
['Teri Yeh Baatein - From "Kho Gaye Hum Kahan"', 'OAFF;Savera;Ankur Tewari'],
['Dil To Bachcha Hai', 'Rahat Fateh Ali Khan'],
['Maula Mere Maula', 'Roop Kumar Rathod;Sayeed Quadri'],
['Tere Hawaale (From "Laal Singh Chaddha")', 'Pritam;Arijit Singh;Shilpa Rao'],
['Naina Da Kya Kasoor', 'Amit Trivedi'],
['Matargashti', 'Mohit Chauhan'],
['Dekha Hazaro Dafaa', 'Arijit Singh;Palak Muchhal;Manoj Muntashir'],
['Ek Dil Ek Jaan (From "Padmaavat")', 'Shivam Pathak;A.M. Turaz'],
['Sajni (From "Laapataa Ladies")', 'Ram Sampath;Arijit Singh;Prashant Pandey'],
['Shaayraana', 'Arijit Singh;Pritam'],
['Ajj Din Chadheya', 'Pritam;Rahat Fateh Ali Khan;Irshad Kamil'],
['Dooriyan', 'Pritam;Mohit Chauhan;Irshad Kamil'],
['Rabba Main Toh Mar Gaya Oye', 'Pritam;Rahat Fateh Ali Khan'],
['Saudebazi (Encore)', 'Pritam;Javed Ali'],
['Ishq Sufiyana (Male)', 'Vishal-Shekhar;Kamal Khan'],
['Zaalima', 'Arijit Singh;Harshdeep Kaur'],
['Phir Bhi Tumko Chaahunga', 'Mithoon;Manoj Muntashir;Arijit Singh;Shashaa Tirupati'],
['Qaafirana', 'Amit Trivedi;Arijit Singh;Nikhita Gandhi'],
['Kesariya (From "Brahmastra")', 'Pritam;Arijit Singh;Amitabh Bhattacharya'],
['Tere Sang Yaara', 'Atif Aslam;Manoj Muntashir'],
['Tujhe Kitna Chahne Lage', 'Arijit Singh;Mithoon'],
['Suno- Na Sangemarmar (From "Youngistaan)', 'Arijit Singh'],
['Khairiyat (Bonus Track)', 'Pritam;Arijit Singh'],
['Tu Chahiye', 'Pritam;Atif Aslam;Amitabh Bhattacharya'],
['Dekha Hazaro Dafaa', 'Arijit Singh;Palak Muchhal;Manoj Muntashir'],
['Hamari Adhuri Kahani (Title Track)', 'Jeet Gannguli;Arijit Singh;Rashmi Virag'],
['Tera Yaar Hoon Main (From "Sonu Ke Titu Ki Sweety")', 'Arijit Singh'],
['Aaoge Jab Tum', 'Rashid Khan;Sandesh Shandilya;Faaiz Anwar'],
['Tu Hi Meri Shab Hai - From "Gangster"', 'Pritam;KK'],
['Billo Rani', 'Pritam;Anand Raj Anand;Richa Sharma'],
['Hum Toh Deewane', 'Rajat Nagpal;Yasser Desai;Rana Sotal'],
['Kuchh Khaas', 'Mohit Chauhan;Neha Bhasin'],
['Yeh Fitoor Mera', 'Amit Trivedi;Arijit Singh'],
['Tenu Sang Rakhna (From "Jigra")', 'Achint;Arijit Singh;Anumita Nadesan;Varun Grover'],
['Yaariyaan - Male', 'Pritam;Irshad Kamil'],
['Jiya Lage Na', 'Sona Mohapatra;Ravindra Upadhyay;Ram Sampath;Javed Akhtar'],
['Saajna', 'Falak Shabbir;Kumaar'],
['Jaane De', 'Atif Aslam;Raj Shekhar;Vishal Mishra'],
['Tere Bina', 'A.R. Rahman;Chinmayi;Murtuza Khan;Qadir Khan'],
['Javeda Zindagi-Tose Naina Lage', 'Kshitij Tarey;Shilpa Rao'],
['Tay Hai', 'Ankit Tiwari;Manoj Muntashir'],
['Hona Tha Pyar', 'Atif Aslam;Hadiqa Kiani'],
['Bairan', 'Banjaare'],
    ['Dhurandhar', 'Shashwat Sachdev;Arijit Singh;Irshad Kamil;Armaan Khan'],
    ['Dhurandhar The Revenge', 'Shashwat Sachdev;Jasmine Sandlas;Satinder Sartaaj'],
    ['Khat', 'Navjot Ahuja'],
    ['Sheesha (Aakhya Mai Aakh Ghali Jo Bairan)', 'Mitta Ror;Swara Verma'],
    ['Sitaare (From "Ikkis")', 'Arijit Singh;White Noise Collectives;Amitabh Bhattacharya'],
    ['Sahiba', 'Aditya Rikhari'],
    ['Dooron Dooron', 'Paresh Pahuja;Shiv Tandan;Meghdeep Bose'],
    ['Majboor', 'Sheheryar Rehan;Zoha Waseem'],
    ['Finding Her', 'Kushagra;Bharath;Saaheal'],
    ['Samjhawan', 'Jawad Ahmad;Shaarib Toshi;Arijit Singh;Shreya Ghoshal'],
    ['Pavazha Malli (From "Think Indie")', 'Sai Abhyankkar;Shruti Haasan;Vivek'],
    ['Arz Kiya Hai | Coke Studio Bharat', 'Anuv Jain'],
    ['Bhediya (Original Motion Picture Soundtrack)', 'Sachin-Jigar;Arijit Singh;Amitabh Bhattacharya'],
    ['P-POP CULTURE', 'Karan Aujla;Ikky'],
    ['Dhurandhar The Revenge', 'Shashwat Sachdev;Bombay Rockers;Irshad Kamil;Khan Saab;Reble;Token;Jasmine Sandlas;Sudhir Yaduvanshi'],
    ['Dhurandhar The Revenge', 'Shashwat Sachdev;Khan Saab;Nusrat Fateh Ali Khan'],
    ['Lost;Found', 'Faheem Abdullah;Rauhan Malik;Amir Ameer'],
    ['Table No. 21 (Original Motion Picture Soundtrack)', 'Gajendra Verma'],
    ['Dhurandhar', 'Shashwat Sachdev;Madhubanti Bagchi;Jasmine Sandlas'],
    ['P-POP CULTURE', 'Karan Aujla;Ikky'],
    ['Saiyaara', 'Tanishk Bagchi;Faheem Abdullah;Arslan Nizami;Irshad Kamil'],
    ['Tum Ho Toh (From "Saiyaara")', 'Vishal Mishra;Hansika Pareek;Raj Shekhar'],
    ['Ishqa Ve', 'Zeeshan Ali;Yuvraj Tung;Sandeep Aulakh;Honey Dhillon'],
    ['Tere Ishk Mein', 'A.R. Rahman;Irshad Kamil'],
    ['Raanjhan (From "Do Patti")', 'Sachet-Parampara;Parampara Tandon;Kausar Munir'],
    ['Shivaay', 'Mithoon;Arijit Singh;Sunidhi Chauhan;Sayeed Quadri'],
    ['Best of Romance: Atif Aslam', 'Atif Aslam;Shreya Ghoshal;Sachin Gupta;Sameer Anjaan'],
    ['Dhurandhar', 'Shashwat Sachdev;Hanumankind;Jasmine Sandlas;Sudhir Yaduvanshi;Charanjit Ahuja;Muhammad Sadiq;Ranjit Kaur;Babu Singh Maan'],
    ['Dhurandhar', 'Shashwat Sachdev;Afsana Khan;Irshad Kamil;Reble'],
    ['Guru (Original Motion Picture Soundtrack)', 'A.R. Rahman;Chinmayi;Murtuza Khan;Qadir Khan'],
    ['Love Wali Feeling: Valentine Special', 'Alka Yagnik;Arijit Singh'],
    ['Dhurandhar The Revenge', 'Shashwat Sachdev;Arijit Singh;Irshad Kamil'],
    ['Jo Tum Mere Ho', 'Anuv Jain'],
    ['Ehsaas', 'Faheem Abdullah;Duha Shah;Vaibhav Pani;Hyder Dar'],
    ['Bairi', 'Virat;Pradeep Solanki;Heena'],
    ['Once Upon Ay Time In Mumbai Dobaara !', 'Pritam;Javed Bashir;Rajat Arora'],
    ['Dhurandhar', 'Shashwat Sachdev;Simran Choudhary'],
    ['Barbaad (From "Saiyaara")', 'The Rish;Jubin Nautiyal'],
    ['Haseen', 'Talwiinder;NDS;Rippy Grewal'],
    ['Dhurandhar', 'Shashwat Sachdev;Reble;Asha Bhosle;R. D. Burman;Majrooh Sultanpuri'],
    ['Love Dose Arijit Singh', 'Arijit Singh;Chinmayi'],
    ['Kailasa', 'Kailash Kher;Paresh Kamath;Naresh Kamath'],
    ['Jhol - Acoustic', 'Maanu;Annural Khalid;Abdullah Siddiqui'],
    ['Youth (Original Motion Picture Soundtrack)', 'G. V. Prakash;Ken Karunaas'],
    ['The Arijit Singh Collection', 'Arijit Singh;Harshdeep Kaur'],
    ['Aaya Sher (From "The Paradise") (Telugu)', 'Anirudh Ravichander;Jangi Reddy;Arjun Chandy;Kasarla Shyam'],
    ['Dhun (From "Saiyaara")', 'Mithoon;Arijit Singh'],
    ['Mann Mera (Original Version)', 'Gajendra Verma'],
    ['High On You', 'Jind Universe'],
];

export default PLAYLIST_SONGS;
